const instructors = [
    {
        id: "instructor-1",
        name: "Suresh Gangavarapu",
        role: "Full Stack Developer",
        color: "bg-blue-600",
        bio: "Suresh Gangavarapu is a seasoned industry professional with extensive experience in Web Development, Marketing, Business, E-commerce. Passionate about teaching and building high-performance systems.",
        courses: 22,
        students: 259554,
        rating: 4.7,
        specializations: ["Web Development", "Marketing", "Business", "E-commerce"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-2",
        name: "Gutlapalli Ramarao",
        role: "Data Scientist",
        color: "bg-teal-600",
        bio: "Gutlapalli Ramarao is a seasoned industry professional with extensive experience in Data Science, Design, AI, Business. Passionate about teaching and building high-performance systems.",
        courses: 11,
        students: 163098,
        rating: 4.8,
        specializations: ["Data Science", "Design", "AI", "Business"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-3",
        name: "Karthik Thanikonda",
        role: "Full Stack Developer",
        color: "bg-red-600",
        bio: "Karthik Thanikonda is a seasoned industry professional with extensive experience in Web Development, Design, Software Architecture. Passionate about teaching and building high-performance systems.",
        courses: 19,
        students: 145740,
        rating: 4.8,
        specializations: ["Web Development", "Design", "Software Architecture"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-4",
        name: "Kavitha Nair",
        role: "Full Stack Developer",
        color: "bg-purple-600",
        bio: "Kavitha Nair is a seasoned industry professional with extensive experience in Web Development, Career. Passionate about teaching and building high-performance systems.",
        courses: 8,
        students: 72540,
        rating: 4.7,
        specializations: ["Web Development", "Career"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-5",
        name: "Srinivas Reddy",
        role: "Mobile App Developer",
        color: "bg-pink-600",
        bio: "Srinivas Reddy is a seasoned industry professional with extensive experience in Mobile, Web Development, Business. Passionate about teaching and building high-performance systems.",
        courses: 12,
        students: 83700,
        rating: 4.8,
        specializations: ["Mobile", "Web Development", "Business"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-6",
        name: "Divya Krishnan",
        role: "UI/UX Designer",
        color: "bg-green-600",
        bio: "Divya Krishnan is a seasoned industry professional with extensive experience in Design, Product, Business. Passionate about teaching and building high-performance systems.",
        courses: 11,
        students: 97800,
        rating: 4.8,
        specializations: ["Design", "Product", "Business"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-7",
        name: "Venkatesh Iyer",
        role: "Data Scientist",
        color: "bg-orange-600",
        bio: "Venkatesh Iyer is a seasoned industry professional with extensive experience in Data Science. Passionate about teaching and building high-performance systems.",
        courses: 3,
        students: 31830,
        rating: 4.8,
        specializations: ["Data Science"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-8",
        name: "Rajesh Naidu",
        role: "Cybersecurity Expert",
        color: "bg-indigo-600",
        bio: "Rajesh Naidu is a seasoned industry professional with extensive experience in Security, Cybersecurity. Passionate about teaching and building high-performance systems.",
        courses: 7,
        students: 52600,
        rating: 4.8,
        specializations: ["Security", "Cybersecurity"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-9",
        name: "Ananya Patel",
        role: "Data Scientist",
        color: "bg-cyan-600",
        bio: "Ananya Patel is a seasoned industry professional with extensive experience in Data Science, Scripting, Data Engineering, Database. Passionate about teaching and building high-performance systems.",
        courses: 19,
        students: 128350,
        rating: 4.7,
        specializations: ["Data Science", "Scripting", "Data Engineering", "Database"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-10",
        name: "Ramesh Kumar",
        role: "Full Stack Developer",
        color: "bg-sky-600",
        bio: "Ramesh Kumar is a seasoned industry professional with extensive experience in Technology, Web Development, Blockchain, Programming. Passionate about teaching and building high-performance systems.",
        courses: 7,
        students: 38000,
        rating: 4.7,
        specializations: ["Technology", "Web Development", "Blockchain", "Programming"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-11",
        name: "Ananya Mehta",
        role: "UI/UX Designer",
        color: "bg-amber-600",
        bio: "Ananya Mehta is a seasoned industry professional with extensive experience in Design. Passionate about teaching and building high-performance systems.",
        courses: 5,
        students: 66100,
        rating: 4.7,
        specializations: ["Design"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-12",
        name: "Aditya Sharma",
        role: "UI/UX Designer",
        color: "bg-violet-600",
        bio: "Aditya Sharma is a seasoned industry professional with extensive experience in Design, Web Development, Game Development, Desktop Development. Passionate about teaching and building high-performance systems.",
        courses: 11,
        students: 96400,
        rating: 4.8,
        specializations: ["Design", "Web Development", "Game Development", "Desktop Development"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-13",
        name: "Moulali Shaik",
        role: "DevOps Engineer",
        color: "bg-rose-600",
        bio: "Moulali Shaik is a seasoned industry professional with extensive experience in DevOps. Passionate about teaching and building high-performance systems.",
        courses: 9,
        students: 64800,
        rating: 4.7,
        specializations: ["DevOps"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-14",
        name: "Sneha Desai",
        role: "Full Stack Developer",
        color: "bg-slate-700",
        bio: "Sneha Desai is a seasoned industry professional with extensive experience in Product, Web Development, Business. Passionate about teaching and building high-performance systems.",
        courses: 4,
        students: 21600,
        rating: 4.6,
        specializations: ["Product", "Web Development", "Business"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-15",
        name: "Priya Menon",
        role: "Full Stack Developer",
        color: "bg-emerald-600",
        bio: "Priya Menon is a seasoned industry professional with extensive experience in Web Development. Passionate about teaching and building high-performance systems.",
        courses: 7,
        students: 46300,
        rating: 4.7,
        specializations: ["Web Development"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-16",
        name: "Dr. Arjun Rao",
        role: "Data Scientist",
        color: "bg-yellow-600",
        bio: "Dr. Arjun Rao is a seasoned industry professional with extensive experience in Data Science, Emerging Technology, Machine Learning, Artificial Intelligence. Passionate about teaching and building high-performance systems.",
        courses: 5,
        students: 53200,
        rating: 4.8,
        specializations: ["Data Science", "Emerging Technology", "Machine Learning", "Artificial Intelligence"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-17",
        name: "Dr. Gutlapalli Ramarao",
        role: "Senior Instructor",
        color: "bg-cyan-700",
        bio: "Dr. Gutlapalli Ramarao is a seasoned industry professional with extensive experience in Artificial Intelligence. Passionate about teaching and building high-performance systems.",
        courses: 1,
        students: 18500,
        rating: 4.9,
        specializations: ["Artificial Intelligence"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-18",
        name: "Dr. Rajesh Kumar",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Dr. Rajesh Kumar is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 4283,
        rating: 4.8,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-19",
        name: "Priya Sharma",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Priya Sharma is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 5729,
        rating: 4.7,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-20",
        name: "Vikram Singh",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Vikram Singh is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 4283,
        rating: 4.5,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-21",
        name: "Dr. Arun Patel",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Dr. Arun Patel is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 4589,
        rating: 4.8,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-22",
        name: "Sneha Reddy",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Sneha Reddy is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 3250,
        rating: 4.9,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-23",
        name: "Karthik Nair",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Karthik Nair is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 3626,
        rating: 4.8,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-24",
        name: "Meera Gupta",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Meera Gupta is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 2607,
        rating: 5.0,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-25",
        name: "Rahul Menon",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Rahul Menon is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 5355,
        rating: 4.8,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-26",
        name: "Ananya Iyer",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Ananya Iyer is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 4426,
        rating: 4.7,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-27",
        name: "Sudeep Bansal",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Sudeep Bansal is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 1981,
        rating: 4.5,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-28",
        name: "Kavita Das",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Kavita Das is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 2620,
        rating: 4.8,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-29",
        name: "Arjun Malhotra",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Arjun Malhotra is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 1182,
        rating: 5.0,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    },
    {
        id: "instructor-30",
        name: "Neha Kapoor",
        role: "Visiting Faculty",
        color: "bg-slate-500",
        bio: "Neha Kapoor is an expert consultant and visiting faculty member at Sukudha Academy, specializing in advanced technical workshops.",
        courses: 0,
        students: 5634,
        rating: 4.6,
        specializations: ["General Engineering", "Soft Skills"],
        social: { linkedin: "#", twitter: "#", website: "#" },
    }
];

module.exports = instructors;
